version: '3.8'

services:
  ui-admin:
    build:
      context: ../
      dockerfile: docker/ui-admin/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - monkeys
    logging:
      driver: 'json-file'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

networks:
  monkeys:
    external: true
